### NumPy Practice

In [2]:
import numpy as np


In [7]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
print(a.ndim)
print(b.ndim)

1
2


In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int64')

In [8]:
a.itemsize

8

### Accessing element in an array or changing it

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
#get a element
print(a[1,3])
print(a[0,5])

11
6


In [18]:
# get a row
print(a[0 ,: ])

[1 2 3 4 5 6 7]


In [17]:
print(a[: ,2])

[ 3 10]


In [19]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### Initialize different types of array


In [21]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones([1,2])

array([[1., 1.]])

In [23]:
np.full([1,4],10)

array([[10, 10, 10, 10]])

In [24]:
np.full_like(a.shape, 10)

array([10, 10])

In [26]:
np.full((2,2) , 99 , dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [3]:
np.random.rand(4,2)

array([[0.19335823, 0.63771082],
       [0.70448329, 0.44121894],
       [0.77127571, 0.38221532],
       [0.75186322, 0.30450147]])

In [4]:
np.random.randint(0,10,(3,3))

array([[9, 6, 5],
       [6, 4, 6],
       [4, 7, 3]], dtype=int32)

In [19]:
np.random.sample(a.shape)

array([0.3214672 , 0.53289803, 0.87294814])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)
r2 = np.repeat(arr,4)
print(r2)

[1 1 1 2 2 2 3 3 3]
[1 1 1 1 2 2 2 2 3 3 3 3]


In [11]:
print(arr+2)

[3 4 5]


In [12]:
print(arr-2)

[-1  0  1]


In [13]:
print(arr*2)

[2 4 6]


### Be careful while trying to copy Arrays

In [14]:
a = np.array([1,2,3])
b = a

In [17]:
print(b)

b[0] = 100
print(a)

[100   2   3]
[100   2   3]


In [18]:
b = a.copy()

### MatheMatics

In [20]:
a = np.array([1,2,3,4])

In [21]:
print(a+2)
print(a-2)
print(a*2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]


In [22]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [23]:
a = np.full((2,3) , 99)
b = np.full((3,2) , 99)

In [27]:
c = np.matmul(a,b)

In [28]:
np.linalg.det(c)

np.float64(1.0696749086491757e-07)

### stats

In [34]:
stats = np.array([[1,2,3,4,5] , [6,7,8,9,10]])

In [35]:
np.min(stats)

np.int64(1)

In [36]:
np.max(stats , axis=1)

array([ 5, 10])

### Reorganising array

In [37]:
before = np.array([[1,2,3,4] , [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [38]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [41]:
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous


In [43]:
filedata = np.genfromtxt('data.txt' , delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
